name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.GH_PAT }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update Version and Merge to Main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Update version in develop
          sed -i "s/^__version__ = .*/__version__ = '${{ github.event.inputs.version }}'/" gitfleet.py
          git add gitfleet.py
      
      - name: Commit, Push and Merge to Main
        run: |
          # Check for changes and commit if needed
          if ! git diff --staged --quiet; then
            git commit -m "Update version to ${{ github.event.inputs.version }}"
            git push origin develop
          else
            echo "No changes to commit"
          fi
          
          # Merge to main with proper history
          git checkout main
          git pull origin main
          git merge --no-ff develop -m "Merge develop: Release ${{ github.event.inputs.version }}"
          
          # Create and push tag
          git tag ${{ github.event.inputs.version }}
          git push origin main
          git push origin ${{ github.event.inputs.version }}
